# Notebook used for data exploration

In [4]:
import pandas as pd

In [5]:
data_path = '../data/atp_matches_2024.csv'
data = pd.read_csv(data_path)

In [33]:
data.tourney_name.unique()

array(['Brisbane', 'United Cup', 'Hong Kong', 'Adelaide', 'Auckland',
       'Australian Open', 'Montpellier', 'Cordoba', 'Dallas', 'Marseille',
       'Delray Beach', 'Buenos Aires', 'Rotterdam', 'Doha', 'Los Cabos',
       'Rio De Janeiro', 'Acapulco', 'Dubai', 'Santiago',
       'Indian Wells Masters', 'Miami Masters', 'Estoril', 'Houston',
       'Marrakech', 'Monte Carlo Masters', 'Barcelona', 'Munich',
       'Bucharest', 'Madrid Masters', 'Rome Masters', 'Geneva', 'Lyon',
       'Roland Garros', 's Hertogenbosch', 'Stuttgart', 'Halle',
       "Queen's Club", 'Mallorca', 'Eastbourne', 'Wimbledon', 'Gstaad',
       'Hamburg', 'Bastad', 'Newport', 'Atlanta', 'Kitzbuhel', 'Umag',
       'Washington', 'Paris Olympics', 'Canada Masters',
       'Cincinnati Masters', 'Winston-Salem', 'Us Open', 'Chengdu',
       'Hangzhou', 'Laver Cup', 'Tokyo', 'Beijing', 'Shanghai Masters',
       'Almaty', 'Antwerp', 'Stockholm', 'Basel', 'Vienna',
       'Paris Masters', 'Belgrade', 'Metz', 'Tour Finals',
       'Next Gen Finals', 'Davis Cup Finals RR: BEL vs BRA',
       'Davis Cup Finals RR: ITA vs BEL',
       'Davis Cup Finals RR: ITA vs BRA',
       'Davis Cup Finals RR: ITA vs NED',
       'Davis Cup Finals RR: NED vs BEL',
       'Davis Cup Finals RR: NED vs BRA',
       'Davis Cup Finals RR: AUS vs CZE',
       'Davis Cup Finals RR: AUS vs ESP',
       'Davis Cup Finals RR: AUS vs FRA',
       'Davis Cup Finals RR: CZE vs ESP',
       'Davis Cup Finals RR: CZE vs FRA',
       'Davis Cup Finals RR: FRA vs ESP',
       'Davis Cup Finals RR: GER vs CHI',
       'Davis Cup Finals RR: GER vs SVK',
       'Davis Cup Finals RR: GER vs USA',
       'Davis Cup Finals RR: SVK vs CHI',
       'Davis Cup Finals RR: USA vs CHI',
       'Davis Cup Finals RR: USA vs SVK',
       'Davis Cup Finals RR: CAN vs ARG',
       'Davis Cup Finals RR: CAN vs FIN',
       'Davis Cup Finals RR: CAN vs GBR',
       'Davis Cup Finals RR: FIN vs ARG',
       'Davis Cup Finals RR: FIN vs GBR',
       'Davis Cup Finals RR: GBR vs ARG',
       'Davis Cup Finals QF: GER vs CAN',
       'Davis Cup Finals SF: GER vs NED',
       'Davis Cup Finals QF: ITA vs ARG',
       'Davis Cup Finals SF: ITA vs AUS',
       'Davis Cup Finals F: ITA vs NED',
       'Davis Cup Finals QF: NED vs ESP',
       'Davis Cup Finals QF: USA vs AUS', 'Davis Cup QLS R1: ARG vs KAZ',
       'Davis Cup QLS R1: CAN vs KOR', 'Davis Cup QLS R1: CHI vs PER',
       'Davis Cup QLS R1: CRO vs BEL', 'Davis Cup QLS R1: CZE vs ISR',
       'Davis Cup QLS R1: FIN vs POR', 'Davis Cup QLS R1: HUN vs GER',
       'Davis Cup QLS R1: NED vs SUI', 'Davis Cup QLS R1: SRB vs SVK',
       'Davis Cup QLS R1: SWE vs BRA', 'Davis Cup QLS R1: TPE vs FRA',
       'Davis Cup QLS R1: UKR vs USA', 'Davis Cup WG1 R1: AUT vs TUR',
       'Davis Cup WG1 R1: CRO vs LTU', 'Davis Cup WG1 R1: EGY vs HUN',
       'Davis Cup WG1 R1: ISR vs UKR', 'Davis Cup WG1 R1: JPN vs COL',
       'Davis Cup WG1 R1: KAZ vs DEN', 'Davis Cup WG1 R1: NOR vs POR',
       'Davis Cup WG1 R1: POL vs KOR', 'Davis Cup WG1 R1: SRB vs GRE',
       'Davis Cup WG1 R1: SUI vs PER', 'Davis Cup WG1 R1: SWE vs IND',
       'Davis Cup WG1 R1: TPE vs BIH', 'Davis Cup WG1 PO: BUL vs BIH',
       'Davis Cup WG1 PO: COL vs LUX', 'Davis Cup WG1 PO: EGY vs ECU',
       'Davis Cup WG1 PO: GRE vs ROU', 'Davis Cup WG1 PO: IRL vs AUT',
       'Davis Cup WG1 PO: LBN vs JPN', 'Davis Cup WG1 PO: LTU vs GEO',
       'Davis Cup WG1 PO: MEX vs DEN', 'Davis Cup WG1 PO: NOR vs LAT',
       'Davis Cup WG1 PO: NZL vs TUR', 'Davis Cup WG1 PO: PAK vs IND',
       'Davis Cup WG1 PO: UZB vs POL', 'Davis Cup WG2 R1: BAR vs PAK',
       'Davis Cup WG2 R1: BOL vs URU', 'Davis Cup WG2 R1: BUL vs ESA',
       'Davis Cup WG2 R1: GEO vs MEX', 'Davis Cup WG2 R1: HKG vs ECU',
       'Davis Cup WG2 R1: LBN vs RSA', 'Davis Cup WG2 R1: MAR vs MON',
       'Davis Cup WG2 R1: NZL vs LUX', 'Davis Cup WG2 R1: ROU vs CHN',
       'Davis Cup WG2 R1: TOG vs LAT', 'Davis Cup WG2 R1: TUN vs IRL',
       'Davis Cup WG2 R1: UZB vs EST', 'Davis Cup WG2 PO: BOL vs THA',
       'Davis Cup WG2 PO: CHN vs SLO', 'Davis Cup WG2 PO: CYP vs MAR',
       'Davis Cup WG2 PO: ESA vs POC', 'Davis Cup WG2 PO: HKG vs ZIM',
       'Davis Cup WG2 PO: IRI vs EST', 'Davis Cup WG2 PO: JAM vs BAR',
       'Davis Cup WG2 PO: PAR vs MON', 'Davis Cup WG2 PO: TOG vs INA',
       'Davis Cup WG2 PO: TUN vs CRC', 'Davis Cup WG2 PO: URU vs MDA',
       'Davis Cup WG2 PO: VIE vs RSA'], dtype=object)

In [41]:
data[data['tourney_name'] == 'Adelaide'][['winner_name', 'loser_name', 'score']]

              winner_name               loser_name              score
83           Jiri Lehecka              Jack Draper        4-6 6-4 6-3
84            Jack Draper         Alexander Bublik         7-6(2) 6-4
85           Jiri Lehecka          Sebastian Korda            6-2 6-1
86            Jack Draper               Tommy Paul            6-1 6-4
87       Alexander Bublik          Lorenzo Musetti     6-3 6-7(4) 7-5
88        Sebastian Korda     Christopher Oconnell            6-4 6-4
89           Jiri Lehecka            Nicolas Jarry            6-4 7-5
90             Tommy Paul                Alex Bolt            6-3 6-2
91            Jack Draper        Miomir Kecmanovic  5-7 7-6(9) 7-6(7)
92        Lorenzo Musetti          Jordan Thompson            6-4 6-1
93       Alexander Bublik             Daniel Evans        4-6 6-2 6-1
94   Christopher Oconnell     Alexander Shevchenko            6-3 6-1
95        Sebastian Korda           Lorenzo Sonego        6-4 7-6(10)
96           Jiri Lehecka            Dusan Lajovic        7-5 4-6 6-3
97          Nicolas Jarry           Matteo Arnaldi  6-7(5) 7-6(7) 6-4
98              Alex Bolt      Thiago Seyboth Wild            6-3 6-2
99      Miomir Kecmanovic       Mackenzie Mcdonald            6-4 6-2
100           Jack Draper           Sebastian Baez            6-1 6-3
101       Jordan Thompson      Facundo Diaz Acosta            6-2 6-2
102          Daniel Evans           Rinky Hijikata            6-3 6-4
103      Alexander Bublik             James Mccabe            6-2 6-3
104  Alexander Shevchenko  Tomas Martin Etcheverry     7-6(4) 4-6 7-5
105  Christopher Oconnell       Arthur Rinderknech            6-4 6-4
106        Lorenzo Sonego         Yannick Hanfmann     7-5 2-6 7-6(9)
107          Jiri Lehecka              Adam Walton            6-1 6-3
108         Dusan Lajovic       Thanasi Kokkinakis        3-6 6-1 6-4
109        Matteo Arnaldi  Bernabe Zapata Miralles            6-4 6-3

In [3]:
data

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-0339,Brisbane,Hard,32,A,20240101,300,105777,2.0,NaN,...,58.0,44.0,16.0,11.0,8.0,9.0,14.0,2570.0,8.0,3660.0
1,2024-0339,Brisbane,Hard,32,A,20240101,299,208029,1.0,NaN,...,35.0,31.0,10.0,11.0,5.0,7.0,8.0,3660.0,39.0,1122.0
2,2024-0339,Brisbane,Hard,32,A,20240101,298,105777,2.0,NaN,...,39.0,24.0,14.0,10.0,5.0,7.0,14.0,2570.0,55.0,902.0
3,2024-0339,Brisbane,Hard,32,A,20240101,297,208029,1.0,NaN,...,51.0,31.0,16.0,10.0,3.0,5.0,8.0,3660.0,116.0,573.0
4,2024-0339,Brisbane,Hard,32,A,20240101,296,126128,NaN,NaN,...,37.0,27.0,16.0,10.0,5.0,8.0,39.0,1122.0,44.0,1021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3071,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,NaN,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
3072,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,NaN,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
3073,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,NaN,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
3074,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,NaN,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
3075,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,NaN,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [13]:
for col in data.columns:
    print(col)

tourney_id
tourney_name
surface
draw_size
tourney_level
tourney_date
match_num
winner_id
winner_seed
winner_entry
winner_name
winner_hand
winner_ht
winner_ioc
winner_age
loser_id
loser_seed
loser_entry
loser_name
loser_hand
loser_ht
loser_ioc
loser_age
score
best_of
round
minutes
w_ace
w_df
w_svpt
w_1stIn
w_1stWon
w_2ndWon
w_SvGms
w_bpSaved
w_bpFaced
l_ace
l_df
l_svpt
l_1stIn
l_1stWon
l_2ndWon
l_SvGms
l_bpSaved
l_bpFaced
winner_rank
winner_rank_points
loser_rank
loser_rank_points

In [ ]:
#Nans per columns
for col in data.columns:
    number_of_nan = data[col].isna().sum()
    if number_of_nan:
        print(f'Number of Nans in {col} : {number_of_nan}')

Number of Nans in winner_seed : 1782
Number of Nans in winner_entry : 2599
Number of Nans in winner_ht : 19
Number of Nans in winner_age : 1
Number of Nans in loser_seed : 2319
Number of Nans in loser_entry : 2358
Number of Nans in loser_ht : 50
Number of Nans in loser_age : 1
Number of Nans in minutes : 238
Number of Nans in w_ace : 60
Number of Nans in w_df : 60
Number of Nans in w_svpt : 60
Number of Nans in w_1stIn : 60
Number of Nans in w_1stWon : 60
Number of Nans in w_2ndWon : 60
Number of Nans in w_SvGms : 61
Number of Nans in w_bpSaved : 60
Number of Nans in w_bpFaced : 60
Number of Nans in l_ace : 60
Number of Nans in l_df : 60
Number of Nans in l_svpt : 60
Number of Nans in l_1stIn : 60
Number of Nans in l_1stWon : 60
Number of Nans in l_2ndWon : 60
Number of Nans in l_SvGms : 61
Number of Nans in l_bpSaved : 60
Number of Nans in l_bpFaced : 60
Number of Nans in winner_rank : 17
Number of Nans in winner_rank_points : 17
Number of Nans in loser_rank : 40
Number of Nans in loser_rank_points : 40

### Ideas

- do not include name or ID

- no binary predictions
- double trainning data by players symmetry

#--- TOURNEY ---
tourney_name
surface
draw_size
tourney_level
tourney_date

#--- PLAYER 1 ---
winner_seed
winner_entry
winner_hand
winner_ht
winner_ioc
winner_age
winner_rank
winner_rank_points

#--- PLAYER 2 ---
loser_seed
loser_entry
loser_hand
loser_ht
loser_ioc
loser_age
loser_rank
loser_rank_points

#--- MATCH ---
best_of
round

#--- OUTCOME ---
score

#TOURNEY to remove

Davis
Next Gen Finals
United Cup